//! An SSH remote: an unprivileged `sshd` on a loopback port, a host key and a
//! passphrase-protected user key generated by `ssh-keygen`, and an ssh
//! configuration naming them. `ssh` reads its per-user configuration from the
//! passwd home directory, not `$HOME`, so the configuration is handed to it
//! through the repository's `core.sshCommand` — the route a user has too.
//! Skips, by name, on a machine without OpenSSH's server.

use std::io::Write;
use std::net::TcpListener;
use std::os::unix::fs::{DirBuilderExt, OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::{Duration, Instant};

use crate::fixtures::Fixture;

/// Where `sshd` is looked for after `PATH`; `scripts/gate.sh` checks the same.
const SBIN: [&str; 2] = ["/usr/sbin", "/usr/local/sbin"];

/// Why the fixture could not be built here; printed, never swallowed.
#[derive(Debug)]
pub struct Unavailable(pub String);

/// Whether the remote's host key is already in `known_hosts`, or must be
/// confirmed on first connection (`StrictHostKeyChecking ask`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HostKey {
    Known,
    Unknown,
}

pub struct SshRemote {
    root: PathBuf,
    home: PathBuf,
    key: PathBuf,
    passphrase: String,
    url: String,
    sshd: Child,
}

impl SshRemote {
    pub fn of(source: &Fixture, host_key: HostKey) -> Result<Self, Unavailable> {
        for program in ["ssh-keygen", "ssh"] {
            if on_path(program).is_none() {
                return Err(Unavailable(format!("{program} is not on PATH")));
            }
        }
        // sshd refuses to run unless invoked by its absolute path; and it lives in an
        // sbin directory, which a non-root PATH commonly lacks (Debian's does not carry
        // /usr/sbin), so those are tried after PATH.
        let Some(sshd) = on_path("sshd").or_else(|| {
            SBIN.iter()
                .map(|dir| Path::new(dir).join("sshd"))
                .find(|candidate| candidate.is_file())
        }) else {
            return Err(Unavailable(format!(
                "sshd is not on PATH or in {}",
                SBIN.join(", ")
            )));
        };
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let unique = NEXT.fetch_add(1, Ordering::Relaxed);
        let root =
            std::env::temp_dir().join(format!("cairn-ssh-remote-{}-{unique}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::DirBuilder::new()
            .mode(0o700)
            .create(&root)
            .map_err(|e| Unavailable(format!("mkdir {}: {e}", root.display())))?;

        let bare = root.join("repo.git");
        run(Command::new("git")
            .args(["clone", "--quiet", "--bare"])
            .arg(source.path())
            .arg(&bare)
            .env("GIT_CONFIG_GLOBAL", "/dev/null")
            .env("GIT_CONFIG_NOSYSTEM", "1"))?;

        let host_key_file = root.join("host_key");
        run(Command::new("ssh-keygen")
            .args(["-q", "-t", "ed25519", "-N", "", "-C", "cairn-host", "-f"])
            .arg(&host_key_file))?;
        let passphrase = format!(
            "generated-{}-{unique}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        );
        let key = root.join("user_key");
        run(Command::new("ssh-keygen")
            .args([
                "-q",
                "-t",
                "ed25519",
                "-N",
                &passphrase,
                "-C",
                "cairn-user",
                "-f",
            ])
            .arg(&key))?;
        let public = std::fs::read_to_string(root.join("user_key.pub"))
            .map_err(|e| Unavailable(format!("reading the user key: {e}")))?;
        write_private(&root.join("authorized_keys"), &public)?;

        let port = free_port()?;
        write_private(
            &root.join("sshd_config"),
            &format!(
                "Port {port}\nListenAddress 127.0.0.1\nHostKey {}\nAuthorizedKeysFile {}\n\
                 PidFile none\nUsePAM no\nStrictModes no\nPasswordAuthentication no\n\
                 KbdInteractiveAuthentication no\nLogLevel ERROR\n",
                host_key_file.display(),
                root.join("authorized_keys").display()
            ),
        )?;
        let log = std::fs::File::create(root.join("sshd.log"))
            .map_err(|e| Unavailable(format!("sshd log: {e}")))?;
        let sshd = Command::new(sshd)
            .args(["-D", "-e", "-f"])
            .arg(root.join("sshd_config"))
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(log)
            .spawn()
            .map_err(|e| Unavailable(format!("could not start sshd: {e}")))?;
        let mut remote = Self {
            root: root.clone(),
            home: root.join("home"),
            key,
            passphrase,
            url: format!("ssh://cairn-fixture/{}", bare.display()),
            sshd,
        };
        remote.wait_until_listening(port)?;

        std::fs::DirBuilder::new()
            .recursive(true)
            .mode(0o700)
            .create(&remote.home)
            .map_err(|e| Unavailable(format!("mkdir {}: {e}", remote.home.display())))?;
        let known_hosts = root.join("known_hosts");
        match host_key {
            HostKey::Known => {
                let host_public = std::fs::read_to_string(root.join("host_key.pub"))
                    .map_err(|e| Unavailable(format!("reading the host key: {e}")))?;
                let mut fields = host_public.split_whitespace();
                let (kind, key) = (fields.next().unwrap_or(""), fields.next().unwrap_or(""));
                write_private(&known_hosts, &format!("[127.0.0.1]:{port} {kind} {key}\n"))?;
            }
            HostKey::Unknown => write_private(&known_hosts, "")?,
        }
        write_private(
            &root.join("ssh_config"),
            &format!(
                "Host cairn-fixture\n  HostName 127.0.0.1\n  Port {port}\n  IdentityFile {}\n  \
                 IdentitiesOnly yes\n  UserKnownHostsFile {}\n  StrictHostKeyChecking {}\n",
                remote.key.display(),
                known_hosts.display(),
                match host_key {
                    HostKey::Known => "yes",
                    HostKey::Unknown => "ask",
                }
            ),
        )?;
        Ok(remote)
    }

    fn wait_until_listening(&mut self, port: u16) -> Result<(), Unavailable> {
        let started = Instant::now();
        while started.elapsed() < Duration::from_secs(10) {
            if std::net::TcpStream::connect(("127.0.0.1", port)).is_ok() {
                return Ok(());
            }
            if let Ok(Some(status)) = self.sshd.try_wait() {
                let log = std::fs::read_to_string(self.root.join("sshd.log")).unwrap_or_default();
                return Err(Unavailable(format!(
                    "sshd exited ({status}) before listening: {log}"
                )));
            }
            std::thread::sleep(Duration::from_millis(50));
        }
        // Read now: the root, log included, goes with this fixture.
        let log = std::fs::read_to_string(self.root.join("sshd.log")).unwrap_or_default();
        Err(Unavailable(format!(
            "sshd did not start listening within 10 seconds: {log}"
        )))
    }

    /// An empty `HOME` for git to run with: nothing of the machine's in it.
    pub fn home(&self) -> &Path {
        &self.home
    }

    /// The value for the fetching repository's `core.sshCommand`: `ssh`
    /// reading this fixture's configuration and nothing of the user's.
    pub fn ssh_command(&self) -> String {
        format!("ssh -F {}", self.root.join("ssh_config").display())
    }

    pub fn url(&self) -> &str {
        &self.url
    }

    pub fn passphrase(&self) -> &str {
        &self.passphrase
    }

    /// The prompt ssh asks for the key's passphrase with.
    pub fn passphrase_prompt(&self) -> String {
        format!("Enter passphrase for key '{}': ", self.key.display())
    }

    /// An `ssh-agent` holding the user key, so no passphrase is ever asked.
    pub fn agent_holding_the_key(&self) -> Result<Agent, Unavailable> {
        for program in ["ssh-agent", "ssh-add"] {
            if on_path(program).is_none() {
                return Err(Unavailable(format!("{program} is not on PATH")));
            }
        }
        let output = Command::new("ssh-agent")
            .arg("-s")
            .output()
            .map_err(|e| Unavailable(format!("could not start ssh-agent: {e}")))?;
        let text = String::from_utf8_lossy(&output.stdout);
        let value = |name: &str| {
            text.lines()
                .find_map(|line| line.strip_prefix(&format!("{name}=")))
                .and_then(|rest| rest.split(';').next())
                .map(str::to_owned)
        };
        let (Some(socket), Some(pid)) = (value("SSH_AUTH_SOCK"), value("SSH_AGENT_PID")) else {
            return Err(Unavailable(format!("ssh-agent printed {text:?}")));
        };
        let agent = Agent {
            socket: PathBuf::from(socket),
            pid,
        };
        // ssh-add reads the passphrase through the askpass path too.
        let askpass = self.root.join("agent-askpass.sh");
        write_private(
            &askpass,
            "#!/bin/sh\ncat \"$CAIRN_FIXTURE_PASSPHRASE_FILE\"\n",
        )?;
        std::fs::set_permissions(&askpass, std::fs::Permissions::from_mode(0o700))
            .map_err(|e| Unavailable(format!("chmod: {e}")))?;
        let passphrase_file = self.root.join("agent-passphrase");
        write_private(&passphrase_file, &self.passphrase)?;
        let added = run(Command::new("ssh-add")
            .arg(&self.key)
            .env_clear()
            .env("PATH", std::env::var_os("PATH").unwrap_or_default())
            .env("SSH_AUTH_SOCK", &agent.socket)
            .env("SSH_ASKPASS", &askpass)
            .env("SSH_ASKPASS_REQUIRE", "force")
            .env("CAIRN_FIXTURE_PASSPHRASE_FILE", &passphrase_file)
            .env("DISPLAY", "")
            .stdin(Stdio::null()));
        let _ = std::fs::remove_file(&passphrase_file);
        added?;
        Ok(agent)
    }
}

impl Drop for SshRemote {
    fn drop(&mut self) {
        let _ = self.sshd.kill();
        let _ = self.sshd.wait();
        let _ = std::fs::remove_dir_all(&self.root);
    }
}

/// A running `ssh-agent`, killed on drop.
pub struct Agent {
    socket: PathBuf,
    pid: String,
}

impl Agent {
    pub fn socket(&self) -> &Path {
        &self.socket
    }
}

impl Drop for Agent {
    fn drop(&mut self) {
        let _ = Command::new("ssh-agent")
            .arg("-k")
            .env("SSH_AGENT_PID", &self.pid)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

/// Where `program` is on this process's `PATH`, if anywhere.
fn on_path(program: &str) -> Option<PathBuf> {
    std::env::split_paths(&std::env::var_os("PATH")?)
        .map(|dir| dir.join(program))
        .find(|candidate| candidate.is_file())
}

fn free_port() -> Result<u16, Unavailable> {
    TcpListener::bind("127.0.0.1:0")
        .and_then(|listener| listener.local_addr())
        .map(|addr| addr.port())
        .map_err(|e| Unavailable(format!("no free loopback port: {e}")))
}

fn write_private(path: &Path, contents: &str) -> Result<(), Unavailable> {
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)
        .map_err(|e| Unavailable(format!("could not write {}: {e}", path.display())))?;
    file.write_all(contents.as_bytes())
        .map_err(|e| Unavailable(format!("could not write {}: {e}", path.display())))
}

fn run(command: &mut Command) -> Result<(), Unavailable> {
    let output = command
        .output()
        .map_err(|e| Unavailable(format!("could not run {command:?}: {e}")))?;
    if output.status.success() {
        Ok(())
    } else {
        Err(Unavailable(format!(
            "{command:?} failed ({}): {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        )))
    }
}
